### ISSUE TITLE
Doesn't seem to be the latest code

### ISSUE THREAD

**Issue by yhjhoo** [clanceyp/monitor-me-jenkins#7]
Please share the latest code, tried to import it in chrome and it doesn't work well.

**Comment by clanceyp** [comment]
Sorry this is a legacy project, it may not work with current Chrome or Jenkins versions. Sadly, I'm not using Jenkins at the moment so can't fix it.

**Comment by yhjhoo** [comment]
Yeah, seems like this software in chrome store is latest version. Could you please push your code to here as well?
