### ISSUE TITLE
Monitor-pro plugin isn't working - please help !!!

### ISSUE THREAD

**Issue by ybello33** [clanceyp/monitor-me-jenkins#8]
Hi 
our jenkins url is configured to work with port 8080 with our domain (not using the http://localhost:8080)
I also download the Jenkins monitor pro plugin and installed
Right now i can;t access into the dashboard beacuse the plugin is rrequired to work with localhost only

any suggesting how i can configure the plugin to work with our url

i'm getting this error
xxx.xxx.com:8080 says
Connection to Jenkins Fails. Check the connection settings.

any help please on this .. -10x

**Comment by clanceyp** [comment]
Have need to remove 'locahost:8080' from the setting and add the full URL of the Jenkins view you want to monitor (not locahost:8080)

**Comment by ybello33** [comment]
Hi
This is what i did and still i got the error 
any suggesting ?

**Comment by clanceyp** [comment]
Try open a browser and paste in whatever URL you added to the extension settings and then add `/api/json` to the end of it (e.g. http://localhost:8080/jenkins/view/All/api/json) and see what response you get.

**Comment by ybello33** [comment]
http://myurl.com:8080/jenkins/view/All/api/json

this is what i'm getting 

HTTP ERROR 404
Problem accessing /jenkins/view/All/api/json. Reason:

    Not Found

**Comment by clanceyp** [comment]
If you go to `http://myurl.com:8080/jenkins/view/All` you see the view ok?

**Comment by ybello33** [comment]
if i put this url  http://myurl.com:8080/view/All/ without "jenkins" it's work

**Comment by ybello33** [comment]
but i see it OK only on browser not when i click on the Monitor pro button inside the Jenkins

**Comment by ybello33** [comment]
The funny things it's all working fine under "Build Monitor Plugin" not on "Monitor Pro Plugin"

**Comment by clanceyp** [comment]
Try putting 'http://myurl.com:8080/view/All' in to the extension settings

**Comment by ybello33** [comment]
it's not working , i really don;t understand what;s wrong 
i really need this plugin working 

please advise

**Comment by ybello33** [comment]
wait....  i try diffrent browser with your recommendation (add the api/json in the end) and now i see the json outputs but i want to see the nice graphics

**Comment by ybello33** [comment]
hi any update ?
